/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAiTeacherRouteImport } from './routes/_authenticated/ai-teacher'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTestsIndexRouteImport } from './routes/_authenticated/tests.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedTestsSlugRouteImport } from './routes/_authenticated/tests.$slug'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results.$attemptId'
import { Route as AuthenticatedAttemptAttemptIdRouteImport } from './routes/_authenticated/attempt.$attemptId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSyllabiRouteImport } from './routes/_authenticated/admin.syllabi'
import { Route as AuthenticatedAdminReviewRouteImport } from './routes/_authenticated/admin.review'
import { Route as AuthenticatedAdminPromosRouteImport } from './routes/_authenticated/admin.promos'
import { Route as AuthenticatedAdminPoolRouteImport } from './routes/_authenticated/admin.pool'
import { Route as AuthenticatedAdminGenerateRouteImport } from './routes/_authenticated/admin.generate'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'
import { Route as ApiPublicPaymentsRazorpayWebhookRouteImport } from './routes/api/public/payments/razorpay-webhook'
import { Route as ApiPublicHooksRefillPoolRouteImport } from './routes/api/public/hooks/refill-pool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiTeacherRoute = AuthenticatedAiTeacherRouteImport.update({
  id: '/ai-teacher',
  path: '/ai-teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsIndexRoute = AuthenticatedTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedTestsSlugRoute = AuthenticatedTestsSlugRouteImport.update({
  id: '/tests/$slug',
  path: '/tests/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttemptAttemptIdRoute =
  AuthenticatedAttemptAttemptIdRouteImport.update({
    id: '/attempt/$attemptId',
    path: '/attempt/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSyllabiRoute =
  AuthenticatedAdminSyllabiRouteImport.update({
    id: '/syllabi',
    path: '/syllabi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewRoute =
  AuthenticatedAdminReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromosRoute =
  AuthenticatedAdminPromosRouteImport.update({
    id: '/promos',
    path: '/promos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPoolRoute = AuthenticatedAdminPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGenerateRoute =
  AuthenticatedAdminGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicPaymentsRazorpayWebhookRoute =
  ApiPublicPaymentsRazorpayWebhookRouteImport.update({
    id: '/api/public/payments/razorpay-webhook',
    path: '/api/public/payments/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefillPoolRoute =
  ApiPublicHooksRefillPoolRouteImport.update({
    id: '/api/public/hooks/refill-pool',
    path: '/api/public/hooks/refill-pool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai-teacher': typeof AuthenticatedAiTeacherRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/admin/pool': typeof AuthenticatedAdminPoolRoute
  '/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/admin/review': typeof AuthenticatedAdminReviewRoute
  '/admin/syllabi': typeof AuthenticatedAdminSyllabiRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/tests/$slug': typeof AuthenticatedTestsSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tests/': typeof AuthenticatedTestsIndexRoute
  '/api/public/hooks/refill-pool': typeof ApiPublicHooksRefillPoolRoute
  '/api/public/payments/razorpay-webhook': typeof ApiPublicPaymentsRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-teacher': typeof AuthenticatedAiTeacherRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/admin/pool': typeof AuthenticatedAdminPoolRoute
  '/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/admin/review': typeof AuthenticatedAdminReviewRoute
  '/admin/syllabi': typeof AuthenticatedAdminSyllabiRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/tests/$slug': typeof AuthenticatedTestsSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tests': typeof AuthenticatedTestsIndexRoute
  '/api/public/hooks/refill-pool': typeof ApiPublicHooksRefillPoolRoute
  '/api/public/payments/razorpay-webhook': typeof ApiPublicPaymentsRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ai-teacher': typeof AuthenticatedAiTeacherRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/_authenticated/admin/pool': typeof AuthenticatedAdminPoolRoute
  '/_authenticated/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/_authenticated/admin/review': typeof AuthenticatedAdminReviewRoute
  '/_authenticated/admin/syllabi': typeof AuthenticatedAdminSyllabiRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/_authenticated/tests/$slug': typeof AuthenticatedTestsSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/tests/': typeof AuthenticatedTestsIndexRoute
  '/api/public/hooks/refill-pool': typeof ApiPublicHooksRefillPoolRoute
  '/api/public/payments/razorpay-webhook': typeof ApiPublicPaymentsRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/ai-teacher'
    | '/billing'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/admin/about'
    | '/admin/generate'
    | '/admin/pool'
    | '/admin/promos'
    | '/admin/review'
    | '/admin/syllabi'
    | '/admin/users'
    | '/attempt/$attemptId'
    | '/results/$attemptId'
    | '/tests/$slug'
    | '/admin/'
    | '/tests/'
    | '/api/public/hooks/refill-pool'
    | '/api/public/payments/razorpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/ai-teacher'
    | '/billing'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/admin/about'
    | '/admin/generate'
    | '/admin/pool'
    | '/admin/promos'
    | '/admin/review'
    | '/admin/syllabi'
    | '/admin/users'
    | '/attempt/$attemptId'
    | '/results/$attemptId'
    | '/tests/$slug'
    | '/admin'
    | '/tests'
    | '/api/public/hooks/refill-pool'
    | '/api/public/payments/razorpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/ai-teacher'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/generate'
    | '/_authenticated/admin/pool'
    | '/_authenticated/admin/promos'
    | '/_authenticated/admin/review'
    | '/_authenticated/admin/syllabi'
    | '/_authenticated/admin/users'
    | '/_authenticated/attempt/$attemptId'
    | '/_authenticated/results/$attemptId'
    | '/_authenticated/tests/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/tests/'
    | '/api/public/hooks/refill-pool'
    | '/api/public/payments/razorpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksRefillPoolRoute: typeof ApiPublicHooksRefillPoolRoute
  ApiPublicPaymentsRazorpayWebhookRoute: typeof ApiPublicPaymentsRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-teacher': {
      id: '/_authenticated/ai-teacher'
      path: '/ai-teacher'
      fullPath: '/ai-teacher'
      preLoaderRoute: typeof AuthenticatedAiTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/': {
      id: '/_authenticated/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof AuthenticatedTestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/tests/$slug': {
      id: '/_authenticated/tests/$slug'
      path: '/tests/$slug'
      fullPath: '/tests/$slug'
      preLoaderRoute: typeof AuthenticatedTestsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attempt/$attemptId': {
      id: '/_authenticated/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/attempt/$attemptId'
      preLoaderRoute: typeof AuthenticatedAttemptAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/syllabi': {
      id: '/_authenticated/admin/syllabi'
      path: '/syllabi'
      fullPath: '/admin/syllabi'
      preLoaderRoute: typeof AuthenticatedAdminSyllabiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/review': {
      id: '/_authenticated/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AuthenticatedAdminReviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promos': {
      id: '/_authenticated/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AuthenticatedAdminPromosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pool': {
      id: '/_authenticated/admin/pool'
      path: '/pool'
      fullPath: '/admin/pool'
      preLoaderRoute: typeof AuthenticatedAdminPoolRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/generate': {
      id: '/_authenticated/admin/generate'
      path: '/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AuthenticatedAdminGenerateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/razorpay-webhook': {
      id: '/api/public/payments/razorpay-webhook'
      path: '/api/public/payments/razorpay-webhook'
      fullPath: '/api/public/payments/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refill-pool': {
      id: '/api/public/hooks/refill-pool'
      path: '/api/public/hooks/refill-pool'
      fullPath: '/api/public/hooks/refill-pool'
      preLoaderRoute: typeof ApiPublicHooksRefillPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminGenerateRoute: typeof AuthenticatedAdminGenerateRoute
  AuthenticatedAdminPoolRoute: typeof AuthenticatedAdminPoolRoute
  AuthenticatedAdminPromosRoute: typeof AuthenticatedAdminPromosRoute
  AuthenticatedAdminReviewRoute: typeof AuthenticatedAdminReviewRoute
  AuthenticatedAdminSyllabiRoute: typeof AuthenticatedAdminSyllabiRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminGenerateRoute: AuthenticatedAdminGenerateRoute,
  AuthenticatedAdminPoolRoute: AuthenticatedAdminPoolRoute,
  AuthenticatedAdminPromosRoute: AuthenticatedAdminPromosRoute,
  AuthenticatedAdminReviewRoute: AuthenticatedAdminReviewRoute,
  AuthenticatedAdminSyllabiRoute: AuthenticatedAdminSyllabiRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAiTeacherRoute: typeof AuthenticatedAiTeacherRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAttemptAttemptIdRoute: typeof AuthenticatedAttemptAttemptIdRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
  AuthenticatedTestsSlugRoute: typeof AuthenticatedTestsSlugRoute
  AuthenticatedTestsIndexRoute: typeof AuthenticatedTestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAiTeacherRoute: AuthenticatedAiTeacherRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAttemptAttemptIdRoute: AuthenticatedAttemptAttemptIdRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
  AuthenticatedTestsSlugRoute: AuthenticatedTestsSlugRoute,
  AuthenticatedTestsIndexRoute: AuthenticatedTestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksRefillPoolRoute: ApiPublicHooksRefillPoolRoute,
  ApiPublicPaymentsRazorpayWebhookRoute: ApiPublicPaymentsRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
