/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ApiAiTeacherRouteImport } from './routes/api/ai-teacher'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAiTeacherRouteImport } from './routes/_authenticated/ai-teacher'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTestsIndexRouteImport } from './routes/_authenticated/tests.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicArticleImageRouteImport } from './routes/api/public/article-image'
import { Route as AuthenticatedTestsSlugRouteImport } from './routes/_authenticated/tests.$slug'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results.$attemptId'
import { Route as AuthenticatedPayPlanRouteImport } from './routes/_authenticated/pay.$plan'
import { Route as AuthenticatedAttemptAttemptIdRouteImport } from './routes/_authenticated/attempt.$attemptId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSyllabiRouteImport } from './routes/_authenticated/admin.syllabi'
import { Route as AuthenticatedAdminReviewRouteImport } from './routes/_authenticated/admin.review'
import { Route as AuthenticatedAdminPromosRouteImport } from './routes/_authenticated/admin.promos'
import { Route as AuthenticatedAdminPoolRouteImport } from './routes/_authenticated/admin.pool'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminGenerateRouteImport } from './routes/_authenticated/admin.generate'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'
import { Route as AuthenticatedAdminArticlesIndexRouteImport } from './routes/_authenticated/admin.articles.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksRefillPoolRouteImport } from './routes/api/public/hooks/refill-pool'
import { Route as AuthenticatedAdminArticlesIdRouteImport } from './routes/_authenticated/admin.articles.$id'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTeacherRoute = ApiAiTeacherRouteImport.update({
  id: '/api/ai-teacher',
  path: '/api/ai-teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiTeacherRoute = AuthenticatedAiTeacherRouteImport.update({
  id: '/ai-teacher',
  path: '/ai-teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsIndexRoute = AuthenticatedTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicArticleImageRoute = ApiPublicArticleImageRouteImport.update({
  id: '/api/public/article-image',
  path: '/api/public/article-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestsSlugRoute = AuthenticatedTestsSlugRouteImport.update({
  id: '/tests/$slug',
  path: '/tests/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayPlanRoute = AuthenticatedPayPlanRouteImport.update({
  id: '/pay/$plan',
  path: '/pay/$plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttemptAttemptIdRoute =
  AuthenticatedAttemptAttemptIdRouteImport.update({
    id: '/attempt/$attemptId',
    path: '/attempt/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSyllabiRoute =
  AuthenticatedAdminSyllabiRouteImport.update({
    id: '/syllabi',
    path: '/syllabi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewRoute =
  AuthenticatedAdminReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromosRoute =
  AuthenticatedAdminPromosRouteImport.update({
    id: '/promos',
    path: '/promos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPoolRoute = AuthenticatedAdminPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGenerateRoute =
  AuthenticatedAdminGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminArticlesIndexRoute =
  AuthenticatedAdminArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefillPoolRoute =
  ApiPublicHooksRefillPoolRouteImport.update({
    id: '/api/public/hooks/refill-pool',
    path: '/api/public/hooks/refill-pool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminArticlesIdRoute =
  AuthenticatedAdminArticlesIdRouteImport.update({
    id: '/articles/$id',
    path: '/articles/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai-teacher': typeof AuthenticatedAiTeacherRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/api/ai-teacher': typeof ApiAiTeacherRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/pool': typeof AuthenticatedAdminPoolRoute
  '/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/admin/review': typeof AuthenticatedAdminReviewRoute
  '/admin/syllabi': typeof AuthenticatedAdminSyllabiRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/pay/$plan': typeof AuthenticatedPayPlanRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/tests/$slug': typeof AuthenticatedTestsSlugRoute
  '/api/public/article-image': typeof ApiPublicArticleImageRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tests/': typeof AuthenticatedTestsIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/api/public/hooks/refill-pool': typeof ApiPublicHooksRefillPoolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/ai-teacher': typeof AuthenticatedAiTeacherRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/api/ai-teacher': typeof ApiAiTeacherRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/pool': typeof AuthenticatedAdminPoolRoute
  '/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/admin/review': typeof AuthenticatedAdminReviewRoute
  '/admin/syllabi': typeof AuthenticatedAdminSyllabiRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/pay/$plan': typeof AuthenticatedPayPlanRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/tests/$slug': typeof AuthenticatedTestsSlugRoute
  '/api/public/article-image': typeof ApiPublicArticleImageRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tests': typeof AuthenticatedTestsIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/api/public/hooks/refill-pool': typeof ApiPublicHooksRefillPoolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ai-teacher': typeof AuthenticatedAiTeacherRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/api/ai-teacher': typeof ApiAiTeacherRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/generate': typeof AuthenticatedAdminGenerateRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/pool': typeof AuthenticatedAdminPoolRoute
  '/_authenticated/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/_authenticated/admin/review': typeof AuthenticatedAdminReviewRoute
  '/_authenticated/admin/syllabi': typeof AuthenticatedAdminSyllabiRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/_authenticated/pay/$plan': typeof AuthenticatedPayPlanRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/_authenticated/tests/$slug': typeof AuthenticatedTestsSlugRoute
  '/api/public/article-image': typeof ApiPublicArticleImageRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/tests/': typeof AuthenticatedTestsIndexRoute
  '/_authenticated/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/api/public/hooks/refill-pool': typeof ApiPublicHooksRefillPoolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/privacy-policy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/admin'
    | '/ai-teacher'
    | '/billing'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/progress'
    | '/api/ai-teacher'
    | '/articles/$slug'
    | '/articles/'
    | '/admin/about'
    | '/admin/generate'
    | '/admin/payments'
    | '/admin/pool'
    | '/admin/promos'
    | '/admin/review'
    | '/admin/syllabi'
    | '/admin/users'
    | '/attempt/$attemptId'
    | '/pay/$plan'
    | '/results/$attemptId'
    | '/tests/$slug'
    | '/api/public/article-image'
    | '/admin/'
    | '/tests/'
    | '/admin/articles/$id'
    | '/api/public/hooks/refill-pool'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/privacy-policy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/ai-teacher'
    | '/billing'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/progress'
    | '/api/ai-teacher'
    | '/articles/$slug'
    | '/articles'
    | '/admin/about'
    | '/admin/generate'
    | '/admin/payments'
    | '/admin/pool'
    | '/admin/promos'
    | '/admin/review'
    | '/admin/syllabi'
    | '/admin/users'
    | '/attempt/$attemptId'
    | '/pay/$plan'
    | '/results/$attemptId'
    | '/tests/$slug'
    | '/api/public/article-image'
    | '/admin'
    | '/tests'
    | '/admin/articles/$id'
    | '/api/public/hooks/refill-pool'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/articles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/privacy-policy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/_authenticated/admin'
    | '/_authenticated/ai-teacher'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/api/ai-teacher'
    | '/articles/$slug'
    | '/articles/'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/generate'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/pool'
    | '/_authenticated/admin/promos'
    | '/_authenticated/admin/review'
    | '/_authenticated/admin/syllabi'
    | '/_authenticated/admin/users'
    | '/_authenticated/attempt/$attemptId'
    | '/_authenticated/pay/$plan'
    | '/_authenticated/results/$attemptId'
    | '/_authenticated/tests/$slug'
    | '/api/public/article-image'
    | '/_authenticated/admin/'
    | '/_authenticated/tests/'
    | '/_authenticated/admin/articles/$id'
    | '/api/public/hooks/refill-pool'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ApiAiTeacherRoute: typeof ApiAiTeacherRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ApiPublicArticleImageRoute: typeof ApiPublicArticleImageRoute
  ApiPublicHooksRefillPoolRoute: typeof ApiPublicHooksRefillPoolRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-teacher': {
      id: '/api/ai-teacher'
      path: '/api/ai-teacher'
      fullPath: '/api/ai-teacher'
      preLoaderRoute: typeof ApiAiTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-teacher': {
      id: '/_authenticated/ai-teacher'
      path: '/ai-teacher'
      fullPath: '/ai-teacher'
      preLoaderRoute: typeof AuthenticatedAiTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/': {
      id: '/_authenticated/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof AuthenticatedTestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/article-image': {
      id: '/api/public/article-image'
      path: '/api/public/article-image'
      fullPath: '/api/public/article-image'
      preLoaderRoute: typeof ApiPublicArticleImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tests/$slug': {
      id: '/_authenticated/tests/$slug'
      path: '/tests/$slug'
      fullPath: '/tests/$slug'
      preLoaderRoute: typeof AuthenticatedTestsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pay/$plan': {
      id: '/_authenticated/pay/$plan'
      path: '/pay/$plan'
      fullPath: '/pay/$plan'
      preLoaderRoute: typeof AuthenticatedPayPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attempt/$attemptId': {
      id: '/_authenticated/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/attempt/$attemptId'
      preLoaderRoute: typeof AuthenticatedAttemptAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/syllabi': {
      id: '/_authenticated/admin/syllabi'
      path: '/syllabi'
      fullPath: '/admin/syllabi'
      preLoaderRoute: typeof AuthenticatedAdminSyllabiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/review': {
      id: '/_authenticated/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AuthenticatedAdminReviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promos': {
      id: '/_authenticated/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AuthenticatedAdminPromosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pool': {
      id: '/_authenticated/admin/pool'
      path: '/pool'
      fullPath: '/admin/pool'
      preLoaderRoute: typeof AuthenticatedAdminPoolRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/generate': {
      id: '/_authenticated/admin/generate'
      path: '/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AuthenticatedAdminGenerateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles/': {
      id: '/_authenticated/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refill-pool': {
      id: '/api/public/hooks/refill-pool'
      path: '/api/public/hooks/refill-pool'
      fullPath: '/api/public/hooks/refill-pool'
      preLoaderRoute: typeof ApiPublicHooksRefillPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/articles/$id': {
      id: '/_authenticated/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminGenerateRoute: typeof AuthenticatedAdminGenerateRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPoolRoute: typeof AuthenticatedAdminPoolRoute
  AuthenticatedAdminPromosRoute: typeof AuthenticatedAdminPromosRoute
  AuthenticatedAdminReviewRoute: typeof AuthenticatedAdminReviewRoute
  AuthenticatedAdminSyllabiRoute: typeof AuthenticatedAdminSyllabiRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminArticlesIdRoute: typeof AuthenticatedAdminArticlesIdRoute
  AuthenticatedAdminArticlesIndexRoute: typeof AuthenticatedAdminArticlesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminGenerateRoute: AuthenticatedAdminGenerateRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPoolRoute: AuthenticatedAdminPoolRoute,
  AuthenticatedAdminPromosRoute: AuthenticatedAdminPromosRoute,
  AuthenticatedAdminReviewRoute: AuthenticatedAdminReviewRoute,
  AuthenticatedAdminSyllabiRoute: AuthenticatedAdminSyllabiRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminArticlesIdRoute: AuthenticatedAdminArticlesIdRoute,
  AuthenticatedAdminArticlesIndexRoute: AuthenticatedAdminArticlesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAiTeacherRoute: typeof AuthenticatedAiTeacherRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedAttemptAttemptIdRoute: typeof AuthenticatedAttemptAttemptIdRoute
  AuthenticatedPayPlanRoute: typeof AuthenticatedPayPlanRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
  AuthenticatedTestsSlugRoute: typeof AuthenticatedTestsSlugRoute
  AuthenticatedTestsIndexRoute: typeof AuthenticatedTestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAiTeacherRoute: AuthenticatedAiTeacherRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedAttemptAttemptIdRoute: AuthenticatedAttemptAttemptIdRoute,
  AuthenticatedPayPlanRoute: AuthenticatedPayPlanRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
  AuthenticatedTestsSlugRoute: AuthenticatedTestsSlugRoute,
  AuthenticatedTestsIndexRoute: AuthenticatedTestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ApiAiTeacherRoute: ApiAiTeacherRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ApiPublicArticleImageRoute: ApiPublicArticleImageRoute,
  ApiPublicHooksRefillPoolRoute: ApiPublicHooksRefillPoolRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
